name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Trigger E2E tests
      if: github.event_name == 'push'  # Solo en push, no en PR
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.DISPATCH_TOKEN }}
        repository: 'walter-scv/cc-e2e-testcicd'  # CAMBIAR por tu repo real
        event-type: run-e2e-tests
        
